package dev.hongan.entity;
// Generated Mar 8, 2024, 10:19:27 AM by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private Serializable categoryName;
	private Set books = new HashSet(0);

	public Category() {
	}

	public Category(Serializable categoryName, Set books) {
		this.categoryName = categoryName;
		this.books = books;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public Serializable getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(Serializable categoryName) {
		this.categoryName = categoryName;
	}

	public Set getBooks() {
		return this.books;
	}

	public void setBooks(Set books) {
		this.books = books;
	}

}
